<?php
/**
 * CatalogAPIApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Efsa\Client\Bigbuy
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BigBuy API
 *
 * OpenAPI spefication to interact with bigbuy.eu
 *
 * The version of the OpenAPI document: v202102
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Efsa\Client\Bigbuy\Test\Api;

use \Efsa\Client\Bigbuy\Configuration;
use \Efsa\Client\Bigbuy\ApiException;
use \Efsa\Client\Bigbuy\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CatalogAPIApiTest Class Doc Comment
 *
 * @category Class
 * @package  Efsa\Client\Bigbuy
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CatalogAPIApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getCatalogAttribute
     *
     * Get a single attribute.
     *
     */
    public function testGetCatalogAttribute()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogAttributeGroup
     *
     * Get a single attribute group.
     *
     */
    public function testGetCatalogAttributeGroup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogAttributeGroups
     *
     * Lists all attribute groups.
     *
     */
    public function testGetCatalogAttributeGroups()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogAttributeLanguages
     *
     * Get languages of a single attribute.
     *
     */
    public function testGetCatalogAttributeLanguages()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogAttributegroupalllanguages
     *
     * Get all languages of a single attribute group.
     *
     */
    public function testGetCatalogAttributegroupalllanguages()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogCategories
     *
     * Lists all categories.
     *
     */
    public function testGetCatalogCategories()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogCategory
     *
     * Returns the selected category.
     *
     */
    public function testGetCatalogCategory()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogCategoryalllanguages
     *
     * Lists all categories.
     *
     */
    public function testGetCatalogCategoryalllanguages()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogLanguages
     *
     * Returns all languages.
     *
     */
    public function testGetCatalogLanguages()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogManufacturer
     *
     * Get a single manufacturer.
     *
     */
    public function testGetCatalogManufacturer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogManufacturers
     *
     * Returns all manufacturers.
     *
     */
    public function testGetCatalogManufacturers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogProduct
     *
     * Returns the selected product.
     *
     */
    public function testGetCatalogProduct()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogProductcategories
     *
     * Get product categories.
     *
     */
    public function testGetCatalogProductcategories()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogProductimages
     *
     * Get a single product images.
     *
     */
    public function testGetCatalogProductimages()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogProductinformation
     *
     * Get a single product.
     *
     */
    public function testGetCatalogProductinformation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogProductinformationalllanguages
     *
     * Get a single product.
     *
     */
    public function testGetCatalogProductinformationalllanguages()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogProductinformationbysku
     *
     * Get a single product by sku.
     *
     */
    public function testGetCatalogProductinformationbysku()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogProducts
     *
     * Returns all products.
     *
     */
    public function testGetCatalogProducts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogProductsinformation
     *
     * Returns all products.
     *
     */
    public function testGetCatalogProductsinformation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogProductsstock
     *
     * Returns all products stock.
     *
     */
    public function testGetCatalogProductsstock()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogProductsstockavailable
     *
     * Returns all products with available stock.
     *
     */
    public function testGetCatalogProductsstockavailable()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalogProductsstockbyreference
     *
     * Returns all selected products stock.
     *
     */
    public function testGetCatalogProductsstockbyreference()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatelogAttributes
     *
     * Lists all attributes.
     *
     */
    public function testGetCatelogAttributes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
