<?php
/**
 * OrderAPIApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Efsa\Client\Bigbuy
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BigBuy API
 *
 * OpenAPI spefication to interact with bigbuy.eu
 *
 * The version of the OpenAPI document: v202102
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Efsa\Client\Bigbuy\Test\Api;

use \Efsa\Client\Bigbuy\Configuration;
use \Efsa\Client\Bigbuy\ApiException;
use \Efsa\Client\Bigbuy\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OrderAPIApiTest Class Doc Comment
 *
 * @category Class
 * @package  Efsa\Client\Bigbuy
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderAPIApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getOrderCarriersStructure
     *
     * Get order carriers structure.
     *
     */
    public function testGetOrderCarriersStructure()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrderShippingAddressStructure
     *
     * Get order shipping address structure.
     *
     */
    public function testGetOrderShippingAddressStructure()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
